const {chromium}=require('./playwright_core.cjs');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||chromium.executablePath(),headless:true,args:['--no-sandbox']});
  const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  const root=process.env.PLANNING_CHECK_BASE;
  await page.goto(root+'/planeamento/gantt/detalhe');
  await page.waitForFunction(()=>document.querySelector('#operations .operations-empty')?.textContent.includes('Planear')).catch(async e=>{throw Error(e.message+'\nNotice: '+await page.locator('#notice').innerText()+'\nOperations: '+await page.locator('#operations').innerText()+'\nErrors: '+JSON.stringify(errors))});
  assert.equal(await page.locator('.operation-row').count(),0);
  await page.goto(root+'/planeamento/carteira');
  await page.locator('#vista').selectOption('of');
  await page.waitForSelector('#rows tr.group');
  await page.locator('#rows .act-plan').first().click();
  await page.waitForFunction(()=>document.querySelector('#notice')?.textContent.includes('planeada'));
  await page.goto(root+'/planeamento/gantt/detalhe');
  await page.locator('.operation-row').first().click();
  await page.waitForFunction(()=>document.querySelector('#machine-choice').options.length>1);
  const machine=await page.locator('#machine-choice option').nth(1).getAttribute('value');
  await page.locator('#machine-choice').selectOption(machine);
  await page.locator('#machine-reason').fill('Ferramentas preparadas para ensaio');
  await page.locator('#edit-form .primary').click();
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Escolha guardada'));
  const id=await page.locator('#scenario').inputValue();
  let scenarios=await (await page.request.get(root+'/planeamento/api/raw/gantt/scenarios')).json();
  let saved=scenarios.scenarios.find(x=>x.id===id);
  assert.equal(Object.keys(saved.definition.machine_overrides).length,1);
  assert.deepEqual(saved.definition.pins,{});
  assert.equal(saved.latest_job_id,null);
  await page.reload();await page.locator('#scenario').selectOption(id);
  await page.locator('.operation-row').first().click();
  await page.waitForFunction(value=>document.querySelector('#machine-choice').value===value,machine);
  await page.screenshot({path:process.env.GANTT_EVIDENCE+'/integrated-machine-menu.png',fullPage:true});
  await page.locator('#restore-auto').click();await page.locator('#edit-form .primary').click();
  await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Escolha guardada'));
  scenarios=await (await page.request.get(root+'/planeamento/api/raw/gantt/scenarios')).json();
  saved=scenarios.scenarios.find(x=>x.id===id);
  assert.deepEqual(saved.definition.machine_overrides,{});
  await page.goto(root+'/planeamento/carteira');await page.locator('#vista').selectOption('of');
  await page.waitForSelector('#rows tr.group');
  await page.locator('#rows .act-clear').first().click();
  await page.waitForFunction(()=>document.querySelector('#notice')?.textContent.includes('limpa'));
  await page.goto(root+'/planeamento/gantt/detalhe');
  await page.waitForFunction(()=>document.querySelector('#operations .operations-empty')?.textContent.includes('Planear'));
  assert.equal(await page.locator('.operation-row').count(),0);
  assert.deepEqual(errors,[]);
  await browser.close();console.log('Carteira → Planear → Gantt → máquina sem hora → persistência → automático → limpar: OK');
})().catch(error=>{console.error(error);process.exit(1)});
