const {chromium}=require(process.env.PLAYWRIGHT_CORE_PATH||'/home/luis/.npm/_npx/fd3bca3c548369c0/node_modules/playwright-core');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/home/luis/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
 const proofFolder=process.env.PLANNING_BROWSER_PROOF_FOLDER||'docs/planeamento-campos-2026-09-21';
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),base=process.env.PLANNING_CHECK_BASE,errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message)});
 await page.goto(base+'/planeamento/manual?of=OF4200&area=perfis&new=1');
 await page.locator('#field-component_ref').waitFor({state:'visible'});
 assert.ok(await page.locator('#search').isHidden());
 assert.equal(await page.getByRole('button',{name:'Adicionar referência nova'}).count(),0);
 assert.equal(await page.getByRole('button',{name:'Origem e histórico',exact:true}).count(),0);
 assert.equal(await page.locator('#actor').count(),0);
 assert.deepEqual(await page.locator('#preparation h2').allTextContents(),['Características de corte','Mais opções','Dados da peça','Trabalho a preparar','Pré-visualização dos cálculos','Guardar']);
 assert.equal(await page.locator('#more-options').evaluate(n=>n.tagName),'SECTION');
 assert.equal(await page.locator('#material-forecast').textContent(),'Calculada ao guardar');
 assert.ok(!await page.locator('#field-abocardar').isChecked());
 await page.locator('#field-component_ref').fill('BROWSER-NEW');
 await page.locator('#field-material_type').selectOption('Perfil U');
 assert.deepEqual(await page.locator('#field-profile option').allTextContents(),['Por definir','UPN50x25','UPN50x38','Outra designação…']);
 await page.locator('#field-profile').selectOption('UPN50x25');
 await page.locator('#field-material_type').selectOption('Tubo redondo');
 assert.equal(await page.locator('#field-profile').inputValue(),'');
 assert.equal(await page.locator('#field-profile').evaluate(n=>n.tagName),'INPUT');
 await page.locator('#field-profile').fill('88.9x3');
 await page.locator('#field-outer_diameter_mm').fill('88,9');
 await page.locator('#field-thickness_mm').fill('3');
 assert.equal(await page.locator('#field-operation').inputValue(),'corte');
 await page.locator('#field-length_mm').fill('1000');
 await page.locator('#field-quantity_required').fill('100');
 for(const id of ['quantity_to_plan','chanfro','ponteira','finish_week','finish_year','weekly_capacity_hours','material_available_date','material_lot','material_request_date'])assert.equal(await page.locator('#field-'+id).count(),0);
 await page.locator('#field-machine').selectOption('MEBA');
 // Evidence/history must preserve in-progress edits without requiring a save.
 await page.getByRole('button',{name:'Ver origem e alterações',exact:true}).click();
 await page.locator('#history-dialog').waitFor({state:'visible'});await page.locator('#history-dialog [data-close]').click();
 await page.getByRole('button',{name:'Ver produção registada',exact:true}).click();
 await page.locator('#evidence-dialog').waitFor({state:'visible'});await page.locator('#evidence-dialog [data-close]').click();
 assert.equal(await page.locator('#field-component_ref').inputValue(),'BROWSER-NEW');
 // Changing mode needs an explicit choice; cancel retains all fields.
 await page.locator('#pdf-link').click();await page.locator('#leave-dialog').waitFor({state:'visible'});
 await page.getByRole('button',{name:'Continuar a editar',exact:true}).click();assert.equal(await page.locator('#field-length_mm').inputValue(),'1000');
 // Always-open supplementary fields and inline numeric validation.
 await page.locator('#field-notes').fill('Conservar esta observação.');
 await page.locator('#field-angle_deg').fill('não é número');
 await page.getByRole('button',{name:'Guardar rascunho',exact:true}).click();await page.locator('#error-angle_deg').filter({hasText:'número'}).waitFor();
 assert.equal(await page.locator('#material-forecast').textContent(),'Calculada ao guardar');
 await page.locator('#field-angle_deg').fill('0');await page.locator('#field-abocardar').check();
 await page.getByRole('button',{name:'Guardar rascunho',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Rascunho guardado'));
 assert.equal(await page.locator('#field-notes').inputValue(),'Conservar esta observação.');
 assert.notEqual(await page.locator('#material-forecast').textContent(),'Calculada ao guardar');
 assert.ok(await page.locator('#field-abocardar').isChecked());
 assert.ok(await page.getByRole('button',{name:'Concluir preparação'}).isDisabled());
 await page.getByRole('button',{name:'Confirmar quantidade em falta',exact:true}).click();
 await page.locator('#conference-form [name=accepted_remaining]').fill('70');await page.locator('#conference-form [name=reason]').fill('Conferência em base descartável.');
 await page.getByRole('button',{name:'Guardar confirmação',exact:true}).click();await page.locator('#conference-dialog').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'Ver produção registada',exact:true}).click();
 await page.locator('#evidence-dialog').waitFor({state:'visible'});
 assert.equal(await page.locator('#evidence-operation option').filter({hasText:'Abocardar'}).count(),1);
 await page.locator('#evidence-operation').selectOption({label:'Abocardar'});
 await page.locator('#evidence-dialog [data-close]').click();assert.equal(await page.locator('#field-operation').inputValue(),'corte');
 await page.screenshot({path:proofFolder+'/manual-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Ver origem e alterações',exact:true}).click();await page.locator('#history-dialog').waitFor({state:'visible'});
 assert.match(await page.locator('#history-content').innerText(),/Utilizador não identificado/);await page.locator('#history-field').selectOption('notes');
 await page.waitForFunction(()=>document.querySelector('#history-content').textContent.includes('Conservar esta observação.'));await page.locator('#history-dialog [data-close]').click();
 await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:proofFolder+'/manual-mobile.png',fullPage:true});
 // A 720 CSS-pixel viewport represents desktop at 200%; it must reflow.
 await page.setViewportSize({width:720,height:525});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 const needId=new URL(page.url()).searchParams.get('necessidade');
 const manualFields=await page.locator('#preparation [id^=field-]').evaluateAll(nodes=>nodes.map(n=>n.id));
 await page.setViewportSize({width:1440,height:1050});
 await page.goto(base+'/planeamento/preparar?document=browser-doc&piece=browser-piece&of=OF9999');
 await page.locator('#pdf-conflict').waitFor({state:'visible'});assert.ok(await page.locator('#preparation').isHidden());await page.getByRole('button',{name:'Usar OF do PDF'}).click();
 await page.locator('#field-component_ref').waitFor({state:'visible'});assert.equal(await page.locator('#field-component_ref').inputValue(),'BROWSER-NEW');
 assert.deepEqual(await page.locator('#preparation [id^=field-]').evaluateAll(nodes=>nodes.map(n=>n.id)),manualFields);
 await page.getByRole('button',{name:'Guardar rascunho',exact:true}).click();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Rascunho guardado'));
 assert.equal(new URL(page.url()).searchParams.get('necessidade'),needId);
 assert.equal(await page.locator('#field-notes').inputValue(),'Conservar esta observação.');
 await page.screenshot({path:proofFolder+'/pdf-desktop.png',fullPage:true});
 const list=await page.request.get(base+'/planeamento/api/necessidades/lista?of=OF4200').then(r=>r.json());assert.equal(list.needs.length,1);
 // Reopening a linked PDF presents human values, never overwrites them with raw OCR.
 await page.locator('#field-notes').fill('Decisão humana depois do PDF.');await page.getByRole('button',{name:'Guardar rascunho',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('Rascunho guardado'));
 await page.goto(base+'/planeamento/preparar?document=browser-doc&piece=browser-piece');await page.locator('#field-component_ref').waitFor({state:'visible'});
 assert.equal(await page.locator('#field-notes').inputValue(),'Decisão humana depois do PDF.');
 await page.getByRole('button',{name:'Guardar rascunho',exact:true}).click();await page.getByRole('button',{name:'Abrir peça seguinte do PDF'}).waitFor({state:'visible'});await page.getByRole('button',{name:'Abrir peça seguinte do PDF'}).click();
 await page.waitForFunction(()=>document.querySelector('#field-component_ref')?.value==='SECOND-PIECE');
 await page.locator('#field-material_type').selectOption('Perfil U');await page.locator('#field-profile').selectOption('__custom__');await page.locator('#field-special_profile').fill('Especial do desenho');assert.ok(await page.locator('#field-geometry').isVisible());
 await page.locator('#manual-link').click();await page.locator('#leave-dialog').waitFor({state:'visible'});await page.getByRole('button',{name:'Descartar alterações'}).click();
 await page.locator('#area').waitFor({state:'visible'});
 // Unknown area stays unselected when no document, plan or prior decision identifies it.
 await page.route('**/api/ordens/OF4200',async route=>{const response=await route.fetch();const json=await response.json();json.context.sources=[];await route.fulfill({response,json})});
 await page.goto(base+'/planeamento/manual?of=OF4200&new=1');await page.locator('#area').waitFor({state:'visible'});assert.equal(await page.locator('#area').inputValue(),'');assert.ok(await page.locator('#catalog-fields').isHidden());
 assert.ok(await page.locator('#field-angle_deg').isVisible());assert.ok(await page.locator('#field-grade').isVisible());assert.ok(await page.locator('#field-length_mm').isVisible());
 assert.deepEqual(errors,[]);console.log(JSON.stringify({manual:true,pdf:true,sharedNeed:true,conferenceWithoutPlan:true,history:true,cpisGuard:true,mobile:true,zoomReflow:true,unsavedGuard:true,pdfOfMismatch:true,unknownArea:true,errors}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
