const {chromium}=require('/home/luis/.npm/_npx/fd3bca3c548369c0/node_modules/playwright-core');
const assert=require('node:assert/strict');
(async()=>{
 if(process.env.PLANNING_TEST_ISOLATED!=='1')throw Error('Disposable database server required');
 const base=process.env.PLANNING_CHECK_BASE;
 const browser=await chromium.launch({executablePath:'/home/luis/.cache/ms-playwright/chromium-1243/chrome-linux64/chrome',headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/planeamento/manual?of=OF4200&area=perfis');
 await page.waitForFunction(()=>document.querySelector('#picking-summary').textContent.includes('21/09/2026'));
 assert.equal(await page.locator('#field-picking_week').inputValue(),'39');
 assert.equal(await page.locator('#field-picking_year').inputValue(),'');
 const sections=await page.locator('#preparation>section>h2').allTextContents();
 assert.deepEqual(sections.slice(0,2),['Dados da peça','Características de corte']);
 assert.match(await page.locator('#picking-summary').innerText(),/ano 2026 assumido/);
 await page.locator('#field-component_ref').fill('BROWSER-AUTO-PICKING');
 await page.locator('#field-material_type').selectOption({label:'Tubo redondo'});
 await page.locator('#field-profile').selectOption({label:'88.9x3'});
 await page.locator('#field-length_mm').fill('1000');
 await page.locator('#field-quantity_required').fill('5');
 const savedResponse=page.waitForResponse(r=>r.url().endsWith('/necessidades/registar'));
 await page.locator('button[name=draft]').click();
 const response=await savedResponse;assert.equal(response.status(),200);
 assert.equal('picking_week' in response.request().postDataJSON().values,false,'automatic suggestion is not a manual decision');
 const saved=await response.json();assert.ok(saved.need_id);
 await page.waitForFunction(()=>!document.querySelector('#after-save').hidden);
 await page.waitForFunction(()=>document.querySelector('#picking-summary').textContent.includes('21/09/2026'));
 let raw=await (await page.request.post(base+'/planeamento/api/raw/consultas',{data:{area:'perfis',selected:[saved.need_id]}})).json();
 assert.equal(raw.rows[0].values.picking_date,'2026-09-21');
 assert.equal(raw.rows[0].values.picking_origin,'Picking · folha');
 await page.locator('#field-picking_week').fill('40');
 await page.waitForFunction(()=>document.querySelector('#picking-summary').textContent.includes('28/09/2026'));
 const updatedResponse=page.waitForResponse(r=>r.url().endsWith('/necessidades/registar'));
 await page.locator('button[name=draft]').click();assert.equal((await updatedResponse).status(),200);
 await page.waitForFunction(()=>!document.querySelector('#after-save').hidden);
 raw=await (await page.request.post(base+'/planeamento/api/raw/consultas',{data:{area:'perfis',selected:[saved.need_id]}})).json();
 assert.equal(raw.rows[0].values.picking_date,'2026-09-28');
 assert.equal(raw.rows[0].values.picking_origin,'Decisão manual');
 await page.reload();
 await page.waitForFunction(()=>document.querySelector('#picking-summary').textContent.includes('28/09/2026'));
 assert.equal(await page.locator('#field-picking_week').inputValue(),'40');
 await page.screenshot({path:process.env.PICKING_EVIDENCE+'/manual-picking.png',fullPage:true});
 await page.goto(base+'/planeamento/raw?area=perfis');
 await page.waitForFunction(()=>document.querySelector('#count').textContent.includes('linhas'));
 assert.ok((await page.locator('#sheet th .label').allTextContents()).includes('Data de Picking'));
 assert.deepEqual(errors,[]);
 await browser.close();console.log('Picking automático: pré-visualização, gravação, RAW, decisão manual e reabertura passaram.');
})().catch(e=>{console.error(e);process.exit(1)});
